# Generated by Django 6.1 on 2026-09-05 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_or_provider', models.CharField(help_text='Country name (for Visa/Passport) or Airline/Provider name (for Air Ticket).', max_length=150)),
                ('service_type', models.CharField(choices=[('VISA', 'Visa'), ('PASSPORT', 'Passport'), ('AIR_TICKET', 'Air Ticket')], max_length=20)),
                ('required_fields', models.JSONField(default=list, help_text='List of fields this country/provider needs, e.g. [{"name": "passport_number", "label": "Passport Number"}, {"name": "date_of_birth", "label": "Date of Birth"}]')),
                ('method', models.CharField(choices=[('API', 'Official API (not yet integrated)'), ('WEBSITE', 'Official Website Only'), ('MANUAL', 'Manual Verification Required')], default='MANUAL', max_length=10)),
                ('official_url', models.URLField(blank=True, help_text='Official government/airline verification website, if one exists.')),
                ('instructions', models.TextField(blank=True, help_text='Any special notes for staff about verifying this country/provider.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Configuration',
                'verbose_name_plural': 'Verification Configurations',
                'ordering': ['service_type', 'country_or_provider'],
                'unique_together': {('country_or_provider', 'service_type')},
            },
        ),
    ]
