# Generated by Django 6.1 on 2026-09-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_checklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationconfig',
            name='official_url',
        ),
        migrations.AddField(
            model_name='verificationconfig',
            name='official_url_1',
            field=models.CharField(blank=True, help_text='Primary official website. Leave/edit freely — plain text placeholder allowed until you add the real link.', max_length=500),
        ),
        migrations.AddField(
            model_name='verificationconfig',
            name='official_url_2',
            field=models.CharField(blank=True, help_text='Secondary official website (optional, for countries with 2 official verification portals).', max_length=500),
        ),
    ]
