# Generated by Django 6.1 on 2026-09-02 10:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('passport_holder_name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(db_index=True, help_text='Used for fast searching across records.', max_length=50)),
                ('number_of_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customer_payment', models.DecimalField(decimal_places=2, help_text='Amount the customer paid us.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('my_payment', models.DecimalField(decimal_places=2, help_text='Our actual cost/payment to the airline or vendor.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit', models.DecimalField(decimal_places=2, editable=False, help_text='Automatically calculated: customer_payment - my_payment.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='air_tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Air Ticket',
                'verbose_name_plural': 'Air Tickets',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
