# Generated by Django 6.1 on 2026-09-02 11:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('passport_holder_name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(db_index=True, max_length=50)),
                ('number_of_manpower', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customer_payment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('my_payment', models.DecimalField(decimal_places=2, help_text='Our actual manpower cost/payment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manpower',
                'verbose_name_plural': 'Manpower Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('passport_holder_name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(db_index=True, max_length=50)),
                ('number_of_passports', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customer_payment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('my_payment', models.DecimalField(decimal_places=2, help_text='Our actual passport cost/payment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('passport_holder_name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(db_index=True, max_length=50)),
                ('number_of_visa', models.PositiveIntegerField(help_text='Number of Visa/Passport for this transaction.', validators=[django.core.validators.MinValueValidator(1)])),
                ('customer_payment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('my_payment', models.DecimalField(decimal_places=2, help_text='Our actual visa cost/payment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
