# Generated by Django 6.1 on 2026-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='J.K. GLOBAL PRIVATE LIMITED', max_length=200)),
                ('managing_director_name', models.CharField(default='Jibon', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Upload the company logo. Recommended: PNG with transparent background, square or wide shape.', null=True, upload_to='site/')),
                ('currency_symbol', models.CharField(default='৳', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
