# Generated by Django 6.1 on 2026-09-04 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_image_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Image Usage',
                'verbose_name_plural': 'AI Image Usage Records',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
