# Generated by Django 6.1 on 2026-09-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiimageusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_accent_color',
            field=models.CharField(default='#3b82f6', help_text='Highlights, active menu, links.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_background_color',
            field=models.CharField(default='#f1f5f9', help_text='Page background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_primary_color',
            field=models.CharField(default='#1e3a5f', help_text='Sidebar and primary buttons.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_text_color',
            field=models.CharField(default='#0f172a', help_text='Main body text color.', max_length=7),
        ),
    ]
