# Generated by Django 6.1 on 2026-09-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_theme_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_hero_image',
            field=models.ImageField(blank=True, help_text='Top welcome banner background image.', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expense_banner_image',
            field=models.ImageField(blank=True, help_text='Expenses section banner image.', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milk_banner_image',
            field=models.ImageField(blank=True, help_text='Milk Business section banner image.', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='travel_banner_image',
            field=models.ImageField(blank=True, help_text='Travel Agency section banner image.', null=True, upload_to='banners/'),
        ),
    ]
