# Generated by Django 6.1 on 2026-09-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_dashboard_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='dashboard_hero_image',
            field=models.FileField(blank=True, help_text='Top welcome banner — image (jpg/png/gif) or video (mp4/webm).', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='expense_banner_image',
            field=models.FileField(blank=True, help_text='Expenses section banner — image or video.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='milk_banner_image',
            field=models.FileField(blank=True, help_text='Milk Business section banner — image or video.', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='travel_banner_image',
            field=models.FileField(blank=True, help_text='Travel Agency section banner — image or video.', null=True, upload_to='banners/'),
        ),
    ]
