# Generated by Django 6.1 on 2026-09-01 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. DANO Full Cream, New Zealand Full Cream', max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from purchase/sale forms but kept for history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milk Product',
                'verbose_name_plural': 'Milk Products',
                'ordering': ['name'],
            },
        ),
    ]
