# Generated by Django 6.1 on 2026-09-02 10:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_milkpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_bags', models.PositiveIntegerField(help_text='Number of 25 KG bags sold.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_bag', models.DecimalField(decimal_places=2, help_text='Selling price per bag in BDT.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Automatically calculated: quantity_bags x price_per_bag.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_sales_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Which product was sold.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='milk.milkproduct')),
            ],
            options={
                'verbose_name': 'Milk Sale',
                'verbose_name_plural': 'Milk Sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
