# Generated by Django 6.1 on 2026-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_milksale'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional product photo.', null=True, upload_to='milk_products/'),
        ),
    ]
