# Generated by Django 6.1 on 2026-09-02 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='documents/originals/')),
                ('detected_blocks', models.JSONField(default=list, help_text='List of {text, left, top, width, height} from OCR.')),
                ('edited_blocks', models.JSONField(default=list, help_text='Same structure as detected_blocks, but with user corrections.')),
                ('exported_file', models.FileField(blank=True, help_text='The saved edited copy, once exported.', null=True, upload_to='documents/exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_edits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Edit',
                'verbose_name_plural': 'Document Edits',
                'ordering': ['-created_at'],
            },
        ),
    ]
