# Generated by Django 6.1 on 2026-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentedit',
            name='added_elements',
            field=models.JSONField(default=list, help_text="List of images/cover-boxes added during editing: {type: 'image'|'cover', src, left, top, width, height} in ORIGINAL image pixel coordinates."),
        ),
    ]
