# Generated by Django 6.1 on 2026-09-03 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.JSONField(default=list, help_text='Ordered list of: {id, source_file_id, page_number, rotation}')),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='pdf_editor/exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Project',
                'verbose_name_plural': 'PDF Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_editor/sources/')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='pdf_editor.pdfproject')),
            ],
        ),
    ]
