# Generated by Django 6.1 on 2026-09-02 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='passport_scans/')),
                ('raw_ocr_text', models.TextField(blank=True, help_text='The full raw text Tesseract extracted from the image.')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=20)),
                ('date_of_expiry', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, max_length=5)),
                ('extraction_successful', models.BooleanField(default=False, help_text='True if MRZ lines were found and parsed successfully.')),
                ('reviewed_and_confirmed', models.BooleanField(default=False, help_text='True once Admin/Staff has reviewed and confirmed the data is correct.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_scans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passport Scan',
                'verbose_name_plural': 'Passport Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
